# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'E-Learning' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for E-Learning
  pod 'FBSDKCoreKit'
  pod 'FBSDKLoginKit'
  pod 'Google/SignIn'

end
